export const TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST'
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS'
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL'

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAIL = 'GET_TODOS_FAIL'

export const DELETE_TODOS_REQUEST = 'DELETE_TODOS_REQUEST'
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS'
export const DELETE_TODOS_FAIL = 'DELETE_TODOS_FAIL'
